#!/usr/bin/env python3
"""Generates src/encoding/code_pages.rs: the upper halves (0x80-0xFF) of the
single-byte code pages GEDCOM files declare, from Python's codec tables.

* WINDOWS-1252 (`CHAR ANSI`, `WINDOWS-1252`, `CP1252`, and the reading of
  `ISO-8859-1`/`LATIN1`): the five bytes cp1252 leaves undefined (0x81, 0x8D,
  0x8F, 0x90, 0x9D) decode to the C1 control of the same value, as the WHATWG
  Encoding Standard does, so no byte is ever lost.
* ISO-8859-15 (`ISO-8859-15`, `LATIN9`).
* IBM PC code page 437 (`IBMPC`, `CP437`).
* Mac OS Roman (`MACINTOSH`, `MACROMAN`), 0xDB being the euro sign.

The lower half is ASCII in every one of them. Standard library only.
Usage: python3 tools/encoding/gen_code_pages.py > src/encoding/code_pages.rs && rustfmt src/encoding/code_pages.rs
"""

import sys

PAGES = [
    ("CP1252", "cp1252", "Windows-1252"),
    ("ISO_8859_15", "iso8859_15", "ISO-8859-15 (Latin-9)"),
    ("CP437", "cp437", "IBM PC code page 437"),
    ("MAC_ROMAN", "mac_roman", "Mac OS Roman"),
]

out = sys.stdout
out.write("// @generated by tools/encoding/gen_code_pages.py from Python's codec tables.\n")
out.write("// Do not edit by hand: re-run the script.\n")
for const, codec, title in PAGES:
    out.write("\n/// %s: the characters of bytes 0x80 to 0xFF.\n" % title)
    out.write("pub(super) static %s: [char; 128] = [\n" % const)
    for b in range(0x80, 0x100):
        try:
            c = bytes([b]).decode(codec)
        except UnicodeDecodeError:
            assert codec == "cp1252" and b in (0x81, 0x8D, 0x8F, 0x90, 0x9D), (codec, b)
            c = chr(b)
        out.write("    '\\u{%04X}',\n" % ord(c))
    out.write("];\n")
